version: "3.9"

services:
  postgres:
    image: postgres:17.6
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: J@tin1234
      POSTGRES_DB: BlogDatas
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=J@tin1234
      - DB_NAME=BlogDatas
      - DB_PORT=5432
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["node", "server.js"]

  frontend:
    build: ./
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
